### ISSUE TITLE
Webpack 5 support?

### ISSUE THREAD

**Issue by dhruvkb** [adambullmer/vue-cli-plugin-browser-extension#126]
Does the plugin support Webpack 5 which will be [the default in Vue CLI 5](https://next.cli.vuejs.org/migrations/migrate-from-v4.html#webpack-5)?

Adding the plugin in a new Vue CLI 5 project (with TypeScript) generates the following error:
```
ERROR  TypeError: Cannot read property 'ignore' of undefined
TypeError: Cannot read property 'ignore' of undefined
    at /Users/x/test_app/node_modules/vue-cli-plugin-browser-extension/index.js:129:20
    at Object.tap (/Users/x/test_app/node_modules/webpack-chain/src/Plugin.js:30:24)
    at /Users/x/test_app/node_modules/vue-cli-plugin-browser-extension/index.js:128:36
    at /Users/x/test_app/node_modules/@vue/cli-service/lib/Service.js:266:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/Users/x/test_app/node_modules/@vue/cli-service/lib/Service.js:266:26)
    at PluginAPI.resolveChainableWebpackConfig (/Users/x/test_app/node_modules/@vue/cli-service/lib/PluginAPI.js:145:25)
    at module.exports (/Users/x/test_app/node_modules/@vue/cli-service/lib/commands/build/resolveAppConfig.js:9:22)
    at build (/Users/x/test_app/node_modules/@vue/cli-service/lib/commands/build/index.js:147:50)
    at /Users/x/test_app/node_modules/@vue/cli-service/lib/commands/build/index.js:69:13
    at Service.run (/Users/x/test_app/node_modules/@vue/cli-service/lib/Service.js:260:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test_app@1.0.0 serve: `vue-cli-service build --mode development --watch`
npm ERR! Exit status 1
npm ERR! 

```

**Comment by Rhilip** [comment]
I also want this feature, Vue CLI 5 is in RC status now, and It is time to update this repo.
In my test, this `TypeError` is because of `copy-webpack-plugin`, as they change the args structure.
However, not only this dependency is old, the `webpack-extension-reloader` dependency is also not support for webpack, and should change it to https://github.com/SimplifyJobs/webpack-ext-reloader.
More the dependency `webextension-polyfill` is also old to use , and can be update to `0.8.0`

**Comment by Rhilip** [comment]
I fork this project and did some work to make it support webpack 5, You can Visit https://github.com/Rhilip/vue-cli-plugin-browser-extension/commit/7e19baf87a1addda8c8445bd9fad62602af9fc41 to see more detail, 
Since mikelxk/vue-cli-plugin-browser-extension lost a dependency and a very import work in new vue-cli 5.x is not done in this project.

Change package.json to `"vue-cli-plugin-browser-extension": "Rhilip/vue-cli-plugin-browser-extension",` , My full merge commit is like https://github.com/ronggang/PT-Plugin-Plus/commit/5b94715941e6d64c5102549635098a6310f784fa

**Comment by sherifmayika** [comment]
Manifest v3 support is there already : [https://github.com/SimplifyJobs/webpack-ext-reloader/issues/28](https://github.com/SimplifyJobs/webpack-ext-reloader/issues/28)

**Comment by Rhilip** [comment]
> Manifest v3 support is there already : [SimplifyJobs/webpack-ext-reloader#28](https://github.com/SimplifyJobs/webpack-ext-reloader/issues/28)

I see this issue and connected pr, however no merge and release. 
Since SimplifyJobs/webpack-ext-reloader lack maintenance, I may want to remove this deps or replace it to another.

**Comment by sherifmayika** [comment]
https://github.com/SimplifyJobs/webpack-ext-reloader is now upgraded to MV3
