### ISSUE TITLE
Error: package.json not found

### ISSUE THREAD

**Issue by lgs** [adambullmer/vue-cli-plugin-browser-extension#35]
```
:~/DEV/EXTENSIONs$ vue add browser-extension

📦  Installing vue-cli-plugin-browser-extension...

+ vue-cli-plugin-browser-extension@0.15.0
updated 1 package and audited 21654 packages in 5.184s
found 0 vulnerabilities

✔  Successfully installed plugin: vue-cli-plugin-browser-extension

 ERROR  Error: package.json not found in /home/lsoave/DEV/EXTENSIONs
Error: package.json not found in /home/lsoave/DEV/EXTENSIONs
    at getPkg (/usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:44:11)
    at invoke (/usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:55:15)
    at module.exports.args (/usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:188:10)
    at add (/usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/add.js:37:5)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**Comment by adambullmer** [comment]
It looks like either you haven't started a vue project yet, or your working directory is not inside of a project directory

**Comment by adambullmer** [comment]
Closing due to inactivity
